In [1]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [3]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [4]:
print(digits.target)

[0 1 2 ... 8 9 8]


In [8]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [9]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100)

In [10]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100, gamma=0.001)

In [12]:
clf.predict(digits.data[-1:])

array([8])

In [16]:
digits.images[-1:]

array([[[ 0.,  0., 10., 14.,  8.,  1.,  0.,  0.],
        [ 0.,  2., 16., 14.,  6.,  1.,  0.,  0.],
        [ 0.,  0., 15., 15.,  8., 15.,  0.,  0.],
        [ 0.,  0.,  5., 16., 16., 10.,  0.,  0.],
        [ 0.,  0., 12., 15., 15., 12.,  0.,  0.],
        [ 0.,  4., 16.,  6.,  4., 16.,  6.,  0.],
        [ 0.,  8., 16., 10.,  8., 16.,  8.,  0.],
        [ 0.,  1.,  8., 12., 14., 12.,  1.,  0.]]])

In [24]:
from sklearn import svm
from sklearn import datasets
clf = svm.SVC()
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf.fit(X, y)

SVC()

In [27]:
import pickle
s = pickle.dumps(clf)
clf2 = pickle.loads(s)
clf2.predict(X[0:1])
y[0]

0

In [30]:
from sklearn.externals import joblib
joblib.dump(clf, "filename.pkl")
clf = jpblib.load("filename.pkl")

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\s1430\anaconda3\envs\myspace\lib\site-packages\sklearn\externals\__init__.py)

In [31]:
import numpy as np
from sklearn import random_projection

In [32]:
rng = np.random.RandomState(0)
X = rng.rand(10, 2000)
X = np.array(X, dtype="float32")
X.dtype

dtype('float32')

In [34]:
transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)
X_new.dtype

dtype('float64')

In [37]:
print(X_new.shape)
print(X.shape)

(10, 1973)
(10, 2000)


In [39]:
from sklearn import datasets
from sklearn.svm import SVC
iris = datasets.load_iris()
clf = SVC()
clf.fit(iris.data, iris.target)

SVC()

In [40]:
list(clf.predict(iris.data[:3]))

[0, 0, 0]

In [41]:
clf.fit(iris.data, iris.target_names[iris.target])

SVC()

In [44]:
list(clf.predict(iris.data[:3]))

['setosa', 'setosa', 'setosa']

In [50]:
import numpy as np
from sklearn.svm import SVC

rng = np.random.RandomState(0)
X = rng.rand(100, 10)
y = rng.binomial(1, 0.5, 100)
X_test = rng.rand(5, 10)

In [51]:
clf = SVC()
clf.set_params(kernel="linear").fit(X, y)
clf.predict(X_test)

array([1, 0, 1, 1, 0])

In [52]:
clf.set_params(kernel="rbf").fit(X, y)
clf.predict(X_test)

array([0, 0, 0, 1, 0])

In [53]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer

In [54]:
X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0, 0, 1, 1, 2]
classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X, y).predict(X)

array([0, 0, 1, 1, 2])

In [56]:
y = LabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [60]:
from sklearn.preprocessing import MultiLabelBinarizer
y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]
y = MultiLabelBinarizer().fit_transform(y)
y

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 1, 0],
       [0, 0, 1, 0, 1]])

In [61]:
classif.fit(X, y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])